Edicion de elementos funcional y se agregaron diseño a los componentes
DeyvidA/reactTodo pull request #4
Opened 2022-01-19 22:34 UTC by DeyvidA

1- Se finalizo la opcion de editar elementos, 
2- Se hicieron cambios en los diseños de los iconos 
3- Se hicieros combios de colores en los distintos componentes

2022-01-20 14:03 UTC, calonzolg requested changes
Dejo varios comentarios para mejorar código

Aun veo bastante inconsistencia en la parte de la declaración de las variables y uso del naming de clases css

2022-01-20 14:03 UTC, calonzolg commented on src/app/index.jsx
> +					<TodoCreate   addTodo={addTodo} />
Acá hay un espacio de más.

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +    const [value, setValue] = React.useState(valueText)
Acá igual tiene un tab extra

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +
Espacio extra

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +
Espacio extra

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +		let algo = sendValue(text);
Variable en español

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +        let valor = event.target.value;
Variable en español

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +        console.log(valor)
Al igual que con node_modules nunca deben ir console.log en los commits

2022-01-20 14:03 UTC, calonzolg commented on src/components/TodoElementEdit/index.jsx
> +            console.log(valor)
Borrar console

2022-01-20 16:35 UTC, haroldut commented on src/components/TodoCreate/index.jsx
> +		} else if (event.charCode === 13 && event.target.value === '') {
¿Esta previamente validado que la cadena no sea solamente uno o mas espacios en blanco tipo ' ' o '   '?

2022-01-20 16:35 UTC, haroldut commented on src/components/TodoItem/index.jsx
>  		let todoEdit = todos.filter((todo) => todo.text === text);
Seria preferible tener un identificador mas unico, ¿Que sucederia si hay dos tareas con el mismo texto?

2022-01-20 16:35 UTC, haroldut commented on src/components/TodoItem/index.jsx
> -		let algo = newValue(text);
¿Que significarian algo y lack? No se logra captar el significado de las variables.

2022-01-21 20:16 UTC, DeyvidA commented on src/components/TodoCreate/index.jsx
> +		} else if (event.charCode === 13 && event.target.value === '') {
en el ultimo commit se agrego una variable que se encargue de solucionar este problema

2022-01-21 20:18 UTC, DeyvidA commented on src/components/TodoItem/index.jsx
> -		let algo = newValue(text);
fueron variables que fueran hechas como pureba, actualmente su nombre fue cambiado por un nombre mas descripitivo en referencia a la funcion que cumplen.

2022-01-21 20:20 UTC, DeyvidA commented on src/components/TodoItem/index.jsx
>  		let todoEdit = todos.filter((todo) => todo.text === text);
Esto fue solucionado siguiendo las orientaciones se agrego un idetificador unico que se encarge de tomar la poscicion especifica que seleccionemos y que no haya ningun problema al seleccionar una tarea con texto igual

2022-01-21 20:22 UTC, DeyvidA commented on src/app/index.jsx
> +					<TodoCreate   addTodo={addTodo} />
Listo, el espacio fue retirado

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +    const [value, setValue] = React.useState(valueText)
Listo, el espacio fue retirado

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +		let algo = sendValue(text);
todas las variables cuyo nombre este en español, se les asigno un nombre en ingles para mantener la consistencia en el codigo

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +        let valor = event.target.value;
todas las variables cuyo nombre este en español, se les asigno un nombre en ingles para mantener la consistencia en el codigo

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +        console.log(valor)
todos los console.log fueron retirados

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +            console.log(valor)
Listo,

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +
Listo, el espacio fue retirado

2022-01-21 20:23 UTC, DeyvidA commented on src/components/TodoElementEdit/index.jsx
> +
Listo, el espacio fue retirado

2022-01-26 16:22 UTC, calonzolg commented
@DeyvidA  En el file `src/app/App.css` aun veo ciertas variaciones en el nombrado de clases. También algunas que están en español

2022-01-26 16:29 UTC, calonzolg requested changes
@DeyvidA Algunos comentarios para que mejores el Código. Anteriormente te dije que implementaras prettierrc y no lo veo en el proyecto.

te puedes guiar con este tutorial: https://medium.com/@icruzr93/c%C3%B3mo-configurar-eslint-y-prettier-en-vscode-para-un-proyecto-en-react-5f6324e582a9

2022-01-26 16:29 UTC, calonzolg commented on src/app/App.css
> +.sectionDates-header{
Cambiar a section-dates-header
```suggestion
.section-dates-header {
```

2022-01-26 16:29 UTC, calonzolg commented on src/app/index.jsx
> +							<div className='reminder reminder1'>
Seguimos con problemas en la consistencia del codigo. arriba veo que estas usuando comillas dobles y aca sencillas. ¿Por qué?

```suggestion
							<div className="reminder reminder1">
```

2022-01-26 16:29 UTC, calonzolg commented on src/app/index.jsx
> +				<section className='sectionDates'>
Acá lo mismo con las comillas

2022-01-26 16:29 UTC, calonzolg commented on src/components/TodoCreate/index.jsx
> +	// };
Si no se esta utilizando removerlo

2022-01-26 16:29 UTC, calonzolg commented on src/components/TodoCreate/index.jsx
> +		let validation = event.trim();
¿Qué es `event`?

2022-01-26 17:21 UTC, DeyvidA commented on src/components/TodoCreate/index.jsx
> +		let validation = event.trim();
se cambio el nombre de esta variable por uno mas descritpivo a la funcion que realiza

2022-01-26 17:22 UTC, DeyvidA commented on src/components/TodoCreate/index.jsx
> +	// };
Problema solucionado en el ultimo commit

2022-01-27 17:01 UTC, calonzolg approved these changes
LGTM

2022-02-03 22:22 UTC, calonzolg requested changes
Para el color también puedes implementar un context para que no estés pasando props de color para cada componente hijo

2022-02-03 22:22 UTC, calonzolg commented on src/app/index.jsx
> +    setColor(color);
Esto hará un bucle infinito

2022-02-03 22:22 UTC, calonzolg commented on src/app/index.jsx
> +      console.log("nell");
Nunca subir console log en los commits

2022-02-03 22:22 UTC, calonzolg commented on src/components/TodoCreate/index.jsx
> +  };
Mantener consistencia en el código

2022-02-03 22:22 UTC, calonzolg commented on src/components/TodoItem/index.jsx
> +  };
Esto se puede simplificar, porque estas asignando un let nada mas

2022-02-03 22:22 UTC, calonzolg commented on src/components/TodoList/index.jsx
>  }) => {
Podrías implementar context veo que pasas varias props

2022-02-14 19:44 UTC, haroldut requested changes
Para las prioridades cambiar el estilo, Poner 4 iconos (3 coronas de color bronce, plata y oro para simbolizar el nivel de prioridad y un icono extra que signifique sin prioridad), al dar click en estos iconos se definira la prioridad clickeada como la actual de la tarea.

En adicion colorear el borde en concordancia con el nivel de prioridad seleccionado.

![image](https://user-images.githubusercontent.com/48334476/153933308-5f95baaf-84cd-456e-93cd-f69e209d605c.png)

Agregar opcion de editar temas.

Cambiar icono de boton de personalizar a palette https://fontawesome.com/icons/palette?s=solid 

Cambiar el selector de temas por un dropdown/select de la siguiente forma
[ Dropdown con el texto del tema seleccionado (+ flecha de dropdown) ] [ Boton de Editar con el icono Pen https://fontawesome.com/icons/pen?s=solid ] [ Boton de Crear con el icono Palette]

[ UT Theme (v) ] [ Edit (pen) ] [ Create (Palette)]

Agregar opcion de seleccionar color de las secciones que aun se ven blancas y de las letras que aun se ven negras.

![image](https://user-images.githubusercontent.com/48334476/153934461-ec685cad-8004-4b54-a810-74278f32e89c.png)

Ya que al crear un tema con primario blanco y secundario negro la mayoria del texto desaparece.

![image](https://user-images.githubusercontent.com/48334476/153934651-3edef463-5280-427e-82b3-7195352a267d.png)

Agregar texto al boton close y ubicarlo paralelo al titulo.

Agregar texto save al boton guardar.

![image](https://user-images.githubusercontent.com/48334476/153934755-6627eee6-b4e1-4a65-9f17-ec2564e8b954.png)

Asegurarse de mantener el tema seleccionado al refrescar.

2022-02-23 17:49 UTC, merged